trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@v2
  displayName: 'Checkout GitHub Repository'

- script: |
    sudo apt-get update
    sudo apt-get install -y apache2
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sudo systemctl start apache2
    sudo systemctl enable apache2
  displayName: 'Install Apache'

- script: |
    sudo rm -rf /var/www/html/*
    sudo cp -r $(Build.SourcesDirectory)/* /var/www/html/
  displayName: 'Deploy Static Website'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'YOUR_SERVICE_CONNECTION'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vm restart --resource-group YOUR_RESOURCE_GROUP --name YOUR_VM_NAME
  displayName: 'Restart Azure VM'
